# Generated by Django 5.1.7 on 2025-03-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_hospital_alter_doctor_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
